### ISSUE TITLE
There are some error messages during booting `PBRP 03-10 [BETA] - A11`

### ISSUE THREAD

**Issue by jfcherng** [Redmi-K30-5G/device_xiaomi_picasso_recovery#2]
Given that [Magisk v21 stable](https://github.com/topjohnwu/Magisk/releases/tag/v21.0), which claims supporting Android 11, just gets released, I upgrade my `K30 5G (picasso)` to 

- `MIUI 12` + `Android 11` (`xiaomi.eu_multi_HMK305G_20.9.24_v12-11.zip`) 
- the untested [`PBRP 03-10 [BETA] - A11`](https://github.com/Redmi-K30-5G/device_xiaomi_picasso_recovery/releases/tag/PBRP-R).

But `PBRP 03-10 [BETA] - A11` (recovery) boots with some error messages as shown in the following screenshot.

![image](https://user-images.githubusercontent.com/6594915/95005806-1c1fae80-062f-11eb-8c28-fe52e2db4746.png)

Not sure if this matters, report it here anyway.

**Comment by masemoel** [comment]
Looks like you can decrypt correctly and I guess you could flash the Android 11 zip as other people could as well :)
I am lost I don't know what fails during the boot process to show those errors.
As it doesn't seems to be so critical, I won't try to fix this error right now: it may be because I'm building in Android 10 source. I will invest about this if the error persists with Android 11's source (when it's released).

**Comment by virogu** [comment]
I'm in the same situation as you, and the files in the data partition are garbled except for the built-in storage

**Comment by masemoel** [comment]
I found that this issue has been solved with the release of xiaomi.eu 12.1 stable build (maybe they messed up with something in vendor).
I flashed it myself and I haven't seen any of those errors anymore.
